//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCar.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenAd
    {
        public string MaAdmin { get; set; }
        public string MaQuyen { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
